export const environment = {
    production: true,
    hmr: false,
    qa: false,
    version: 0.4,
    APIAd: 'https://gwseguridadad.prd-bo-proc.financieraoh.local/gwseguridadad',
    APICtaAho: 'https://bscuentadebito.prd-bo-proc.financieraoh.local/bscuentadebito',
    APITrxAho: 'https://bstrxdebito.prd-bo-proc.financieraoh.local/bstrxdebito',
    APICliAho: 'https://bsclientedebito.prd-bo-proc.financieraoh.local/bsclientedebito',
    APICliAgo: 'https://bsclienteagora-produccion.prd-apps.financieraoh.local/bsclienteagora',
    APICamMon: 'https://bstasacambio.prd-gke.financieraoh.local/bstasacambio',
    APIBloMas: 'https://bsbloqueosmasivosohpay.prd-bo-proc.financieraoh.local/bsbloqueosmasivosohpay',
    APITarOhP: 'https://bstarjetasohpay.prd-gke.financieraoh.local/bstarjetasohpay',
    APIUtilAho: 'https://bsutilsahorros.prd-gke.financieraoh.local/bsutilsahorros',
    APIUtilIntOpay: 'https://bsinteropayctos.prd-gke.financieraoh.local/bsinteropayctos',
    APICtaAhoMig: 'https://bsctasahorros.prd-gke.financieraoh.local/bsctasahorros',
    APICarDig: 'https://apis-saas-prd.financieraoh.local/carteradigital',
    APIGeeTarOh: 'https://apis-saas-prd.tarjetaoh.com.pe/public/auth',
      APIAccesoCuentaEmpresa: 'https://bsaccesosctaemp.des-gke.financieraoh.local/bsaccesosctaemp',
    APICatalo: '',
    APIAjuAho: '',
    APIUrl: '',
    PrivateKeyEncodedBase64: '#{Team-Implementaciones-web-aba2-PrivateKeyEncodedBase64}#',
    ClientIdTarOh: '#{Team-Implementaciones-web-aba2-ClientIdTarOh}#',
    ClientSecretTarOh: '#{Team-Implementaciones-web-aba2-ClientSecretTarOh}#',    
};
