export const environment = {
    production: false,
    hmr: false,
    qa: true,
    version: 0.4,
    APIAd: 'https://gwseguridadad.qas-bo-proc.financieraoh.local/gwseguridadad',
    APICtaAho: 'https://bscuentadebito.qas-bo-proc.financieraoh.local/bscuentadebito',      
    APITrxAho: 'https://bstrxdebito.qas-bo-proc.financieraoh.local/bstrxdebito',
    APICliAho: 'https://bsclientedebito.qas-bo-proc.financieraoh.local/bsclientedebito',
    // APICtaAho: 'http://localhost:3000/api/bscuentadebito',
    // APITrxAho: 'http://localhost:3000/api/bstrxdebito',
    // APICliAho: 'http://localhost:3000/api/bsclientedebito',

    APICliAgo: 'https://bsclienteagora-testqas.qas-apps.financieraoh.local/bsclienteagora',
    APICamMon: 'https://bstasacambio.qas-gke.financieraoh.local/bstasacambio',
    //APICamMon: 'http://localhost:3000/api/bstasacambio',
    APIBloMas: 'https://bsbloqueosmasivosohpay.qas-bo-proc.financieraoh.local/bsbloqueosmasivosohpay',
    APITarOhP: 'https://bstarjetasohpay.qas-gke.financieraoh.local/bstarjetasohpay',
    APIUtilAho: 'https://bsutilsahorros.qas-gke.financieraoh.local/bsutilsahorros',
    APIUtilIntOpay: 'https://bsinteropayctos.qas-gke.financieraoh.local/bsinteropayctos',
    APICtaAhoMig: 'https://bsctasahorros.qas-gke.financieraoh.local/bsctasahorros',
    APICarDig: 'https://apis-saas-qas.financieraoh.local/carteradigital',
    APIGeeTarOh: 'https://apis-saas-qas.tarjetaoh.com.pe/public/auth',
      APIAccesoCuentaEmpresa: 'https://bsaccesosctaemp.des-gke.financieraoh.local/bsaccesosctaemp',
    APICatalo: '',
    APIAjuAho: '',
    APIUrl: '',
    PrivateKeyEncodedBase64: '#{Team-Implementaciones-web-aba2-PrivateKeyEncodedBase64}#',
    ClientIdTarOh: '#{Team-Implementaciones-web-aba2-ClientIdTarOh}#',
    ClientSecretTarOh: '#{Team-Implementaciones-web-aba2-ClientSecretTarOh}#',
    FlgDesarrollo: true
};
